### ISSUE TITLE
Relative paths to input/ouput folder is not supported

### ISSUE THREAD

**Issue by tmshv** [designunit/geophoto#9]
1. Support paths relative to script directory
2. Support paths relative to user home using `os.path.expanduser`

**Comment by tmshv** [comment]
I will add a couple of use cases to describe this task more precisely.

1. `python3 geophoto.py ../images ../../output/dataset ...`
2. `python3 geophoto.py ~/images ~/output/dataset ...`

Am I clear?

**Comment by modernpacifist** [comment]
I think yes
